@Library('Shared') _
pipeline {
    agent any

    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }

    stages {
        stage("Workspace cleanup") {
            steps {
                script {
                    cleanWs()
                }
            }
        }

        stage('Git: Code Checkout') {
            steps {
                script {
                    code_checkout("https://github.com/DEVKUMARSAINI545/Cloud-Native-E-Commerce-Platform-Onsko-ECommerce-product-.git", "main")
                }
            }
        }

        stage('Verify: Docker Image Tags') {
            steps {
                script {
                    echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                    echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                }
            }
        }

        stage("Update: Kubernetes manifests") {
            steps {
                script {
                    dir('k8s') {
                        sh """
                            sed -i -e 's|onsko-backend-beta.*|onsko-backend-beta:${params.BACKEND_DOCKER_TAG}|g' backend.yml
                        """
                        sh """
                            sed -i -e 's|onsko-frontend-beta.*|onsko-frontend-beta:${params.FRONTEND_DOCKER_TAG}|g' frontend.yml
                        """
                    }
                }
            }
        }

        stage("Git: Code update and push to GitHub") {
            steps {
                script {
                    withCredentials([gitUsernamePassword(credentialsId: 'Github', gitToolName: 'Default')]) {
                        sh """
                            git status
                            git add .
                            git commit -m "Updated environment variables by Dev Kumar Saini" || echo "Nothing to commit by Dev Kumar Saini"
                            git push https://github.com/DEVKUMARSAINI545/Cloud-Native-E-Commerce-Platform-Onsko-ECommerce-product-.git main
                        """
                    }
                }
            }
        }
    }

    // post {
    //     success {
    //         emailext(
    //             attachLog: true,
    //             to: 'devsaini27806@gmail.com',
    //             from: 'devsaini27806@gmail.com',
    //             subject: "✅ Onsko Application Deployed - ${currentBuild.result}",
    //             mimeType: 'text/html',
    //             body: """
    //                 <h2>Build Successful!</h2>
    //                 <p><b>Project:</b> ${env.JOB_NAME}</p>
    //                 <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
    //                 <p><b>Build URL:</b> <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
    //             """
    //         )
    //     }

    //     failure {
    //         emailext(
    //             attachLog: true,
    //             to: 'devsaini27806@gmail.com',
    //             from: 'devsaini27806@gmail.com',
    //             subject: "❌ Onsko Application Failed - ${currentBuild.result}",
    //             mimeType: 'text/html',
    //             body: """
    //                 <h2>Build Failed!</h2>
    //                 <p><b>Project:</b> ${env.JOB_NAME}</p>
    //                 <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
    //                 <p><b>Check Logs:</b> <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
    //             """
    //         )
    //     }
    // }
     post {
        success {
            script {
                emailext attachLog: true,
                from: 'devsaini27806@gmail.com',
                subject: "Onsko Application has been updated and deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'devsaini27806@gmail.com',
            mimeType: 'text/html'
            }
        }
      failure {
            script {
                emailext attachLog: true,
                from: 'devsaini27806@gmail.com',
                subject: "Onsko Application build failed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'devsaini27806@gmail.com',
            mimeType: 'text/html'
            }
        }
    
}
}
