apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: onsko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: devsaini255/new-onsko-backend:v4
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: onsko
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
