apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: onsko
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: devsaini255/onsko-backend-beta:v200
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        env:
         - name: MONGODB_URI
           value: "mongodb+srv://DevSaini:1256@cluster0.pugztbw.mongodb.net/onsko"

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: onsko
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31100
  type: NodePort
